### ISSUE TITLE
unknown command "eth-keys" for "sommelier"

### ISSUE THREAD

**Issue by jayjay-crypto** [PeggyJV/testnets#6]
Hello,
I got an error when I run the command:
sommelier eth-keys add.
The command returns the error:
unknown command "eth-keys" for "sommelier".
And eth-keys does not appear in available commands for sommelier

**Comment by jackzampolin** [comment]
Hey @jayjay-crypto thanks for reporting this! Appreciate that you are trying things out. Will make sure to ping this when we do another testnet that includes validators and not just devs

**Comment by jayjay-crypto** [comment]
Thank you,
We are too impatient to be able to take part in the adventure....
